baseURL = "https://liuyunyishui.github.io/blog"
languageCode = "zh-cn"
hasCJKLanguage =  true

publishDir="docs"

uglyURLs = true
#canonifyURLs=true
#relativeURLs = true

enableEmoji = true

# 禁用页面种类
disableKinds = ["RSS"]

disqusShortname = "liuyunyishui" # delete this to disable disqus comments
# Enter your tracking code to enable Google Analytics
#googleAnalytics = ""

# 对应html>head>title、Title属性
title = "流云居"
description = "流云的Blog"
paginate = 3

mathJax = false
# 主题设置
theme = "liuyun"
# 主题属性
    
[permalinks]
  post = "/:year/:month/:title/"

#菜单
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post.html"
    name = "Archives"
    weight = 2

[[menu.main]]
    url = "/categories.html"
    name = "Categories"
    weight = 3

[[menu.main]]
    url = "/about.html"
    name = "About"
    weight = 4

[params]
    # 图片设置
    # static/images/icons
    favicon_ico_sizes = "16x16 32x32"
    #favicon_png_sizes = "96x96"

    favicon = "favicon.jpg"
    #favicon_ico = "favicon.ico"
    #favicon_png = "favicon.png"
    #favicon_svg = "favicon.svg"

    appleicon = "favicon.ico"

    accent = "SlateBlue"
    showBorder = true
    backgroundColor = "azure"

    font = "KaiTi"    # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "solarized-dark"
    highlightLanguages = ["java", "javascript", "sql", "go", "shell"]

    profilePic = "liuyun.jpg"
    author = "流云"
    description = "Personal blog"
    githubUsername = "liuyunyishui"

    
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

#[[params.social]]
#    url = "mailto:liuyunyishui@gmail.com"
#    name = "envelope-o"
#    weight = 1

[[params.social]]
    #title = "微博"
    name = "weibo"
    url = "https://weibo.com/5628184250"
    target = "_blank"
    weight = 1

[[params.social]]
    url = "https://github.com/liuyunyishui"
    name = "github"
    target = "_blank"
    weight = 2

[[params.social]]
    url = "https://stackoverflow.com/users/10763940"
    name = "stack-overflow"
    target = "_blank"
    weight = 3

[[params.social]]
    url = "https://twitter.com/liuyunyishui/"
    name = "twitter"
    target = "_blank"
    weight = 4

[[params.social]]
    url = "https://www.facebook.com/liuyunyishui"
    name = "facebook-f"
    target = "_blank"
    weight = 5
    
# Footer settings
[params.footer]
    # If copyright is not set, author is used
    copyright = "流云"

# Page license
[params.license]  
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"